// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHasherMock is an autogenerated mock type for the PasswordHasher type
type PasswordHasherMock struct {
	mock.Mock
}

// Hash provides a mock function with given fields: password
func (_m *PasswordHasherMock) Hash(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Verify provides a mock function with given fields: password, hash
func (_m *PasswordHasherMock) Verify(password, hash string) (bool, error) {
	ret := _m.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(password, hash)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(password, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewPasswordHasherMock creates a new instance of PasswordHasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPasswordHasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasherMock {
	mock := &PasswordHasherMock{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
