// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	auth "transfers-api/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// TokenManagerMock is an autogenerated mock type for the TokenManager type
type TokenManagerMock struct {
	mock.Mock
}

// GenerateAccessToken provides a mock function with given fields: userID, role
func (_m *TokenManagerMock) GenerateAccessToken(userID, role string) (string, error) {
	ret := _m.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(userID, role)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GenerateRefreshToken provides a mock function with given fields: userID
func (_m *TokenManagerMock) GenerateRefreshToken(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ValidateToken provides a mock function with given fields: token
func (_m *TokenManagerMock) ValidateToken(token string) (*auth.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewTokenManagerMock creates a new instance of TokenManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManagerMock {
	mock := &TokenManagerMock{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
