// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TransfersPublisherMock is an autogenerated mock type for the TransfersPublisher type
type TransfersPublisherMock struct {
	mock.Mock
}

// Publish provides a mock function with given fields: operation, transferID
func (_m *TransfersPublisherMock) Publish(operation string, transferID string) error {
	ret := _m.Called(operation, transferID)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(operation, transferID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with no fields
func (_m *TransfersPublisherMock) Read() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransfersPublisherMock creates a new instance of TransfersPublisherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransfersPublisherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransfersPublisherMock {
	mock := &TransfersPublisherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
