// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	services "transfers-api/internal/services"

	mock "github.com/stretchr/testify/mock"
)

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

// Register provides a mock function with given fields: ctx, username, email, password, role
func (_m *AuthServiceMock) Register(ctx context.Context, username, email, password, role string) (services.RegisterResult, error) {
	ret := _m.Called(ctx, username, email, password, role)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 services.RegisterResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (services.RegisterResult, error)); ok {
		return rf(ctx, username, email, password, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) services.RegisterResult); ok {
		r0 = rf(ctx, username, email, password, role)
	} else {
		r0 = ret.Get(0).(services.RegisterResult)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, username, email, password, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *AuthServiceMock) Login(ctx context.Context, email, password string) (services.LoginResult, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 services.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (services.LoginResult, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) services.LoginResult); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(services.LoginResult)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *AuthServiceMock) RefreshToken(ctx context.Context, refreshToken string) (services.LoginResult, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 services.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (services.LoginResult, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) services.LoginResult); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(services.LoginResult)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Logout provides a mock function with given fields: ctx, userID
func (_m *AuthServiceMock) Logout(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
