// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	auth "transfers-api/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// TokenValidatorMock is an autogenerated mock type for the TokenValidator type
type TokenValidatorMock struct {
	mock.Mock
}

// ValidateToken provides a mock function with given fields: token
func (_m *TokenValidatorMock) ValidateToken(token string) (*auth.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewTokenValidatorMock creates a new instance of TokenValidatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenValidatorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenValidatorMock {
	mock := &TokenValidatorMock{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
