// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "transfers-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// TransfersServiceMock is an autogenerated mock type for the TransfersService type
type TransfersServiceMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, transfer
func (_m *TransfersServiceMock) Create(ctx context.Context, transfer models.Transfer) (string, error) {
	ret := _m.Called(ctx, transfer)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) (string, error)); ok {
		return rf(ctx, transfer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) string); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(context.Context, models.Transfer) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TransfersServiceMock) GetByID(ctx context.Context, id string) (models.Transfer, error) {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}
	var r0 models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Transfer)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Update provides a mock function with given fields: ctx, transfer
func (_m *TransfersServiceMock) Update(ctx context.Context, transfer models.Transfer) error {
	ret := _m.Called(ctx, transfer)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) error); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TransfersServiceMock) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GetByUserID provides a mock function with given fields: ctx, id
func (_m *TransfersServiceMock) GetByUserID(ctx context.Context, id string) ([]models.Transfer, error) {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}
	var r0 []models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transfer)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewTransfersServiceMock creates a new instance of TransfersServiceMock.
func NewTransfersServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransfersServiceMock {
	mock := &TransfersServiceMock{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
